In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = np.random.randn(7,4)

In [3]:
data

array([[-0.18640129, -0.69569675, -0.61921295, -2.00879591],
       [ 0.05935961,  1.04891261, -0.17910073, -0.24669615],
       [ 0.04998635, -0.19533704,  0.48480783, -0.24046599],
       [ 1.9645661 , -0.31694481,  1.07204386, -2.00398287],
       [ 0.8184592 ,  1.43288544,  1.98947755,  1.44478911],
       [-0.42553305,  1.11670549, -0.60515537, -1.06205475],
       [ 0.08829322,  1.53527   , -0.01729636, -1.74095528]])

In [4]:
data[data<0] = 0
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.05935961, 1.04891261, 0.        , 0.        ],
       [0.04998635, 0.        , 0.48480783, 0.        ],
       [1.9645661 , 0.        , 1.07204386, 0.        ],
       [0.8184592 , 1.43288544, 1.98947755, 1.44478911],
       [0.        , 1.11670549, 0.        , 0.        ],
       [0.08829322, 1.53527   , 0.        , 0.        ]])

In [7]:
names = np.array(['bob','joe','will','bob','joe','will','will'])
names

array(['bob', 'joe', 'will', 'bob', 'joe', 'will', 'will'], dtype='<U4')

In [8]:
names

array(['bob', 'joe', 'will', 'bob', 'joe', 'will', 'will'], dtype='<U4')

In [10]:
names[names =='joe'] = 7
names

array(['bob', '7', 'will', 'bob', '7', 'will', 'will'], dtype='<U4')

In [12]:
arr = np.empty([8,4])
arr

array([[9.42661990e-312, 1.08694442e-321, 0.00000000e+000,
        0.00000000e+000],
       [1.89146896e-307, 5.02034658e+175, 8.47272093e+165,
        1.74652250e-076],
       [1.96655431e+160, 1.39722326e-075, 3.88267385e-057,
        4.26399373e-096],
       [1.12855837e+277, 5.24957395e+233, 8.87696970e+247,
        3.98472128e+252],
       [5.04621343e+180, 1.94918963e-153, 7.69165785e+218,
        7.49874301e+247],
       [2.59903827e-144, 6.03387673e+174, 1.17049904e-046,
        1.22150551e+165],
       [2.12644105e+160, 3.98450681e+252, 6.00736842e-067,
        3.45944505e+097],
       [2.74448875e-057, 4.26593158e+126, 1.28625693e+248,
        9.46215455e-053]])

In [14]:
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [15]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [16]:
arr[[4,-3,0,6]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [19]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [20]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [21]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [22]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [23]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [24]:
arr.swapaxes(0,1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])