In [30]:
import numpy as np

# 1D ARRAY PRACTICE

In [31]:
# Create a 1D array from 10 to 20 (inclusive)
arr1 = np.arange(10, 21)
print("1D Array:", arr1)

# Sum, Mean, Standard Deviation
print("Sum:", arr1.sum())
print("Mean:", arr1.mean())
print("Standard Deviation:", arr1.std())

# Convert array to float datatype
arr1_float = arr1.astype(float)
print("Converted to float:", arr1_float)

# Multiply each element by 2 and subtract 5
modified_arr1 = arr1 * 2 - 5
print("Multiply by 2 and subtract 5:", modified_arr1)

# Select elements greater than 15
greater_than_15 = arr1[arr1 > 15]
print("Elements > 15:", greater_than_15)

# Reverse the array using slicing
reversed_arr1 = arr1[::-1]
print("Reversed Array:", reversed_arr1)


1D Array: [10 11 12 13 14 15 16 17 18 19 20]
Sum: 165
Mean: 15.0
Standard Deviation: 3.1622776601683795
Converted to float: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
Multiply by 2 and subtract 5: [15 17 19 21 23 25 27 29 31 33 35]
Elements > 15: [16 17 18 19 20]
Reversed Array: [20 19 18 17 16 15 14 13 12 11 10]


# 2D ARRAY PRACTICE

In [32]:
# Create a 2D array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("\n2D Array:\n", arr2)

# Shape, number of dimensions, size
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Size:", arr2.size)

# Extract second row
second_row = arr2[1]
print("Second Row:", second_row)

# Extract third column
third_column = arr2[:, 2]
print("Third Column:", third_column)

# Bottom-right 2x2 sub-array
bottom_right = arr2[1:, 1:]
print("Bottom-right 2x2:\n", bottom_right)

# Change datatype to float64
arr2_float = arr2.astype(np.float64)
print("Float64 Array:\n", arr2_float)

# Add 5 to every element
print("Add 5:\n", arr2 + 5)

# Element-wise multiplication
print("Element-wise multiplication:\n", arr2 * arr2)

# Row-wise and Column-wise sum
print("Row-wise sum:", arr2.sum(axis=1))
print("Column-wise sum:", arr2.sum(axis=0))



2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Size: 9
Second Row: [4 5 6]
Third Column: [3 6 9]
Bottom-right 2x2:
 [[5 6]
 [8 9]]
Float64 Array:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Add 5:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Element-wise multiplication:
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]


# 3D ARRAY PRACTICE

In [33]:
# Create a 3D array of shape (2,3,4) using numbers 1 to 24
arr3 = np.arange(1, 25).reshape(2, 3, 4)
print("\n3D Array:\n", arr3)

# Shape, dimensions, size
print("Shape:", arr3.shape)
print("Dimensions:", arr3.ndim)
print("Size:", arr3.size)

# Extract first 2D block
first_block = arr3[0]
print("First 2D Block:\n", first_block)

# Extract last row of second 2D block
last_row_second_block = arr3[1, -1, :]
print("Last row of second block:", last_row_second_block)

# Convert to int32
arr3_int = arr3.astype(np.int32)
print("Converted to int32:\n", arr3_int)

# Multiply all elements by 3 and subtract 2
print("Multiply by 3 and subtract 2:\n", arr3 * 3 - 2)



3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
Dimensions: 3
Size: 24
First 2D Block:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Last row of second block: [21 22 23 24]
Converted to int32:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Multiply by 3 and subtract 2:
 [[[ 1  4  7 10]
  [13 16 19 22]
  [25 28 31 34]]

 [[37 40 43 46]
  [49 52 55 58]
  [61 64 67 70]]]


# ARITHMETIC OPERATIONS

In [34]:
# Create two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\na + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)

# Create 2D array
arr = np.array([[1, 2],
                [3, 4]])

# Add 10 to all elements
print("Add 10:\n", arr + 10)

# Multiply array by 2
print("Multiply by 2:\n", arr * 2)

# Element-wise square
print("Square:\n", arr ** 2)

# Sum, mean, min, max
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Min:", arr.min())
print("Max:", arr.max())

# Dot product of two 1D arrays
dot_product = np.dot([1, 2, 3], [4, 5, 6])
print("Dot Product:", dot_product)

# Square root of array elements
sqrt_arr = np.sqrt([4, 9, 16, 25])
print("Square Roots:", sqrt_arr)



a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]
Add 10:
 [[11 12]
 [13 14]]
Multiply by 2:
 [[2 4]
 [6 8]]
Square:
 [[ 1  4]
 [ 9 16]]
Sum: 10
Mean: 2.5
Min: 1
Max: 4
Dot Product: 32
Square Roots: [2. 3. 4. 5.]


# DATA TYPE RELATED QUESTIONS

In [35]:
# Integer array to float64
int_arr = np.array([1, 2, 3])
float_arr = int_arr.astype(np.float64)
print("\nInteger to Float64:", float_arr)

# Float array to int32
float_arr2 = np.array([1.2, 2.8, 3.9])
int32_arr = float_arr2.astype(np.int32)
print("Float to Int32:", int32_arr)

# Boolean 2D array to integer
bool_arr = np.array([[True, False],
                     [False, True]])
print("Boolean to Int:\n", bool_arr.astype(int))

# Check datatype and change it
print("Original dtype:", arr.dtype)
changed_arr = arr.astype(float)
print("Changed dtype:", changed_arr.dtype)



Integer to Float64: [1. 2. 3.]
Float to Int32: [1 2 3]
Boolean to Int:
 [[1 0]
 [0 1]]
Original dtype: int64
Changed dtype: float64
