In [1]:
import numpy as np

# (a) Mean, Standard Deviation, Variance along 2nd axis

In [ ]:
arr_a = np.random.randint(1, 50, size=(4, 5))
print("2D Random Array:\n", arr_a)

mean = np.mean(arr_a, axis=1)
std_dev = np.std(arr_a, axis=1)
variance = np.var(arr_a, axis=1)

print("\nMean along 2nd axis:", mean)
print("Standard Deviation along 2nd axis:", std_dev)
print("Variance along 2nd axis:", variance)

2D Random Array:
 [[37 18 20 19 28]
 [14 49  4 28 44]
 [10  6  2 43 43]
 [49 24 33 12  7]]

Mean along 2nd axis: [24.4 27.8 20.8 25. ]
Standard Deviation along 2nd axis: [ 7.2277244  17.13942823 18.30191247 15.05988048]
Variance along 2nd axis: [ 52.24 293.76 334.96 226.8 ]


# (b) Create m x n array, print properties, reshape to n x m

In [ ]:
m = int(input("\nEnter number of rows (m): "))
n = int(input("Enter number of columns (n): "))

arr_b = np.random.randint(1, 100, size=(m, n))

print("\nOriginal Array:\n", arr_b)
print("Shape:", arr_b.shape)
print("Type:", type(arr_b))
print("Data Type:", arr_b.dtype)

reshaped_arr = arr_b.reshape(n, m)
print("\nReshaped Array (n x m):\n", reshaped_arr)


Original Array:
 [[75 20 76 77 34]
 [64 42 69  9 61]
 [23  1  5 63 38]
 [75 69 41 98 98]
 [48 65 81 89 35]]
Shape: (5, 5)
Type: <class 'numpy.ndarray'>
Data Type: int32

Reshaped Array (n x m):
 [[75 20 76 77 34]
 [64 42 69  9 61]
 [23  1  5 63 38]
 [75 69 41 98 98]
 [48 65 81 89 35]]


# (c) Check zero, non-zero and NaN values in 1D array

In [1]:
arr_c = np.array([0, 3, np.nan, 5, 0, 8, np.nan,10])
reshaped_arr = arr_c.reshape(2, 4)
print("\n1D Array:", arr_c)
print(reshaped_arr)

zero_indices = np.where(arr_c == 0)
nonzero_indices = np.where(arr_c != 0)
nan_indices = np.where(np.isnan(arr_c))

print("Indices of Zero elements:", zero_indices[0])
print("Indices of Non-Zero elements:", nonzero_indices[0])
print("Indices of NaN elements:", nan_indices[0])

NameError: name 'np' is not defined

# (d) Covariance and Correlation

In [ ]:
Array1 = np.random.randint(10)
Array2 = np.random.randint(10)
Array3 = np.random.randint(10)

Array4 = Array3 - Array2

Array5 = 2 * Array1

print("\nArray1:", Array1)
print("Array4 (Array3 - Array2):", Array4)
print("Array5 (2 * Array1):", Array5)

covariance = np.cov(Array1, Array4)
print("\nCovariance of Array1 and Array4:\n", covariance)

correlation = np.corrcoef(Array1, Array5)
print("\nCorrelation of Array1 and Array5:\n", correlation)


Array1: [0.22538238 0.52000066 0.77012129 0.82948509 0.53911251 0.00700006
 0.06651208 0.91438332 0.6822622  0.63395106]
Array4 (Array3 - Array2): [-0.14419335 -0.73553625 -0.17041136  0.08510214 -0.36163195  0.20474342
 -0.22814698 -0.34455232  0.50711796 -0.02252325]
Array5 (2 * Array1): [0.45076476 1.04000132 1.54024258 1.65897018 1.07822502 0.01400012
 0.13302417 1.82876665 1.3645244  1.26790213]

Covariance of Array1 and Array4:
 [[ 0.10101832 -0.00443112]
 [-0.00443112  0.11697898]]

Correlation of Array1 and Array5:
 [[1. 1.]
 [1. 1.]]


# (e) Sum of first half & product of second half

In [ ]:
Array1 = np.random.randint(1, 10, 10)
Array2 = np.random.randint(1, 10, 10)

print("\nArray1:", Array1)
print("Array2:", Array2)

first_half_sum = np.sum(Array1[:5]) + np.sum(Array2[:5])

second_half_product = np.prod(Array1[5:]) * np.prod(Array2[5:])

print("Sum of first half of both arrays:", first_half_sum)
print("Product of second half of both arrays:", second_half_product)



Array1: [8 6 8 3 8 2 7 7 8 9]
Array2: [1 2 9 8 4 3 9 6 6 6]
Sum of first half of both arrays: 57
Product of second half of both arrays: 41150592
