In [1]:
import numpy as np

# Section A: Fancy Indexing (1D Arrays)

In [2]:
# Create 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print("Original Array:", arr)

# 1. Select elements at positions [0, 2, 4, 6]
selected_positions = arr[[0, 2, 4, 6]]
print("Positions [0,2,4,6]:", selected_positions)

# 2. Extract values [20, 50, 70] using fancy indexing
values_extracted = arr[[1, 4, 6]]
print("Extracted values [20,50,70]:", values_extracted)

# 3. Reverse array using fancy indexing
reverse_arr = arr[[6, 5, 4, 3, 2, 1, 0]]
print("Reversed array:", reverse_arr)

# 4. Replace values at positions [1, 3, 5] with 0
arr_copy = arr.copy()
arr_copy[[1, 3, 5]] = 0
print("After replacing positions [1,3,5] with 0:", arr_copy)

# 5. Select all elements greater than 30 (boolean indexing)
greater_than_30 = arr[arr > 30]
print("Elements greater than 30:", greater_than_30)

Original Array: [10 20 30 40 50 60 70]
Positions [0,2,4,6]: [10 30 50 70]
Extracted values [20,50,70]: [20 50 70]
Reversed array: [70 60 50 40 30 20 10]
After replacing positions [1,3,5] with 0: [10  0 30  0 50  0 70]
Elements greater than 30: [40 50 60 70]


# Section B: Boolean Indexing

In [3]:
arr2 = np.array([12, 45, 67, 23, 89, 10, 55])
print("\nBoolean Indexing Array:", arr2)

# 6. Select values greater than 50
greater_than_50 = arr2[arr2 > 50]
print("Values greater than 50:", greater_than_50)

# 7. Replace all values less than 20 with -1
arr2_modified = arr2.copy()
arr2_modified[arr2_modified < 20] = -1
print("Replace values < 20 with -1:", arr2_modified)

# 8. Count elements between 20 and 60
count_between = np.sum((arr2 >= 20) & (arr2 <= 60))
print("Count between 20 and 60:", count_between)

# 9. Extract only even numbers
even_numbers = arr2[arr2 % 2 == 0]
print("Even numbers:", even_numbers)

# 10. Create new array with squares of values greater than 40
squares_gt_40 = arr2[arr2 > 40] ** 2
print("Squares of values > 40:", squares_gt_40)


Boolean Indexing Array: [12 45 67 23 89 10 55]
Values greater than 50: [67 89 55]
Replace values < 20 with -1: [-1 45 67 23 89 -1 55]
Count between 20 and 60: 3
Even numbers: [12 10]
Squares of values > 40: [2025 4489 7921 3025]


# Section C: Fancy & Boolean Indexing on 2D Arrays

In [4]:
arr3 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
print("\n2D Array:\n", arr3)

# 11. Select diagonal elements [10, 50, 90]
diagonal_elements = arr3[[0, 1, 2], [0, 1, 2]]
print("Diagonal elements:", diagonal_elements)

# 12. Extract elements at positions (0,2), (1,1), (2,0)
specific_elements = arr3[[0, 1, 2], [2, 1, 0]]
print("Selected elements:", specific_elements)

# 13. Select first and third rows
selected_rows = arr3[[0, 2], :]
print("First and third rows:\n", selected_rows)

# 14. Select second and third columns
selected_columns = arr3[:, [1, 2]]
print("Second and third columns:\n", selected_columns)

# 15. Replace all values less than 40 with 0
arr3_modified = arr3.copy()
arr3_modified[arr3_modified < 40] = 0
print("Values < 40 replaced with 0:\n", arr3_modified)


2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Diagonal elements: [10 50 90]
Selected elements: [30 50 70]
First and third rows:
 [[10 20 30]
 [70 80 90]]
Second and third columns:
 [[20 30]
 [50 60]
 [80 90]]
Values < 40 replaced with 0:
 [[ 0  0  0]
 [40 50 60]
 [70 80 90]]


# Section D: Transpose and Swap Axes

In [5]:
# Create 3D array
arr4 = np.arange(24).reshape(2, 3, 4)
print("\n3D Array:\n", arr4)

# 16. Print shape of the array
print("Original Shape:", arr4.shape)

# 17. Apply transpose (1, 0, 2)
transposed_1 = arr4.transpose(1, 0, 2)
print("Shape after transpose(1,0,2):", transposed_1.shape)

# 18. Apply transpose (2, 1, 0)
transposed_2 = arr4.transpose(2, 1, 0)
print("Shape after transpose(2,1,0):", transposed_2.shape)

# 19. Swap axis 0 and axis 1
swapped = arr4.swapaxes(0, 1)
print("Shape after swapaxes(0,1):", swapped.shape)

# 20. Check if swapaxes(0,1) and transpose(1,0,2) give same shape
print("Same shape?:", swapped.shape == transposed_1.shape)



3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Original Shape: (2, 3, 4)
Shape after transpose(1,0,2): (3, 2, 4)
Shape after transpose(2,1,0): (4, 3, 2)
Shape after swapaxes(0,1): (3, 2, 4)
Same shape?: True
